### ISSUE TITLE
The Application Znode Tool.app can't be opened - Mojave 10.14.6

### ISSUE THREAD

**Issue by goodc0re** [zcoinofficial/znode-tool-evo#4]
I downloaded  znode-tool-1.0.1-beta2-osx-amd64.zip
unzipped it, moved it into my Applications folder and when trying to open it, I only get a message:

**The Application "Znode Tool.app" can't be opened.** 

Mojave 10.14.6

Permissions look as follows: 

drwxr-xr-x@   3 user  group    96B Jun 21 06:47 Znode Tool.app

**Comment by a-bezrukov** [comment]
Please try the 1.0.1 release.

**Comment by a-bezrukov** [comment]
If the issue persists, please reopen the issue and attach the output of a znode-tool run via console. I am running it like this:
```
pc:~ user$ cd ~/Downloads/znode-tool.app/Contents/MacOS/
pc:MacOS user$ ./znode-tool 
```
Please remove all personal information (at list your PC name and the user name) from the output.

**Comment by goodc0re** [comment]
The application doesn't start by clicking on the application shortcut (same error). 

The Znode Tool starts via the command line, there is a lot of output: 


./znode-tool 
INFO:root:===========================================================================
INFO:root:Application started (v 1.0.1)
INFO:root:Environmnent:

(leaving out a lot here, let me know if you need it) 

ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
ERROR:root:String decryption error: 
Traceback (most recent call last):
  File "cryptography/fernet.py", line 104, in _verify_signature
  File "cryptography/hazmat/primitives/hmac.py", line 66, in verify
  File "cryptography/hazmat/backends/openssl/hmac.py", line 74, in verify
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app_config.py", line 585, in simple_decrypt
  File "app_utils.py", line 200, in decrypt
  File "cryptography/fernet.py", line 75, in decrypt
  File "cryptography/fernet.py", line 117, in _decrypt_data
  File "cryptography/fernet.py", line 106, in _verify_signature
cryptography.fernet.InvalidToken
