### ISSUE TITLE
Trezor 1.9.4 breaks ZnodeTool - Answer from Trezor

### ISSUE THREAD

**Issue by jTd7bPLFb** [zcoinofficial/znode-tool-evo#9]
https://github.com/trezor/trezor-firmware/issues/1576#issuecomment-823569482

prusnak commented 3 minutes ago • 
edited 
From the log:

ERROR:root:Exception calling sign_tx function
Traceback (most recent call last):
  File "hw_intf.py", line 75, in catch_hw_client
  File "hw_intf.py", line 348, in sign_tx
  File "wnd_utils.py", line 151, in run_thread_dialog
  File "wnd_utils.py", line 139, in call
  File "thread_fun_dlg.py", line 366, in run
  File "hw_intf.py", line 330, in sign
  File "hw_intf_trezor.py", line 466, in sign_tx
  File "trezorlib/tools.py", line 233, in wrapped_f
  File "trezorlib/btc.py", line 167, in sign_tx
  File "trezorlib/tools.py", line 233, in wrapped_f
  File "trezorlib/client.py", line 222, in call
trezorlib.exceptions.TrezorFailure: DataError: Expected input with amount
ERROR:dmt.wallet_dlg:Exception when preparing the transaction.
The client now needs to provide amount for all inputs. Please open issue for ZnodeMasternodeTool and show them this error log.

**Comment by a-bezrukov** [comment]
Fixed, please download the 1.0.3 release
